version: '3.9'

services:
  nginx:
    image: netycbo/emne_8_cloud:nginx
    container_name: nginx
    ports:
      - "80:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/Nginx/nginx.conf:ro 
    depends_on:
      - api
    networks:
      - backend 

  api:
    image: netycbo/emne_8_cloud:api
    container_name: api
    ports:
      - "8080:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=mydb;User=myuser;Password=mypassword;
    depends_on:
      - mysql
    networks:
      - backend 

  mysql:
    image: netycbo/emne_8_cloud:mysql
    container_name: mysql
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend 

volumes:
  db_data:

networks:
  backend:
   driver: bridge  